// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VMTO.Infrastructure.Persistence;

#nullable disable

namespace VMTO.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302024326_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VMTO.Domain.Aggregates.Artifact.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_uri");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("VMTO.Domain.Aggregates.Connection.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.HasKey("Id");

                    b.ToTable("connections", (string)null);
                });

            modelBuilder.Entity("VMTO.Domain.Aggregates.License.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivationBindings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("activation_bindings");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("features");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int>("MaxConcurrentJobs")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrent_jobs");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signature");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("licenses", (string)null);
                });

            modelBuilder.Entity("VMTO.Domain.Aggregates.MigrationJob.JobStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("LogsUri")
                        .HasColumnType("text")
                        .HasColumnName("logs_uri");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("job_steps", (string)null);
                });

            modelBuilder.Entity("VMTO.Domain.Aggregates.MigrationJob.MigrationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<Guid>("SourceConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_connection_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy");

                    b.Property<Guid>("TargetConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_connection_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("VMTO.Infrastructure.Persistence.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("VMTO.Domain.Aggregates.Artifact.Artifact", b =>
                {
                    b.OwnsOne("VMTO.Domain.ValueObjects.Checksum", "Checksum", b1 =>
                        {
                            b1.Property<Guid>("ArtifactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("checksum_algorithm");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("checksum_value");

                            b1.HasKey("ArtifactId");

                            b1.ToTable("artifacts");

                            b1.WithOwner()
                                .HasForeignKey("ArtifactId");
                        });

                    b.Navigation("Checksum")
                        .IsRequired();
                });

            modelBuilder.Entity("VMTO.Domain.Aggregates.Connection.Connection", b =>
                {
                    b.OwnsOne("VMTO.Domain.ValueObjects.EncryptedSecret", "EncryptedSecret", b1 =>
                        {
                            b1.Property<Guid>("ConnectionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CipherText")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("cipher_text");

                            b1.Property<string>("KeyId")
                                .HasColumnType("text")
                                .HasColumnName("key_id");

                            b1.HasKey("ConnectionId");

                            b1.ToTable("connections");

                            b1.WithOwner()
                                .HasForeignKey("ConnectionId");
                        });

                    b.Navigation("EncryptedSecret")
                        .IsRequired();
                });

            modelBuilder.Entity("VMTO.Domain.Aggregates.MigrationJob.JobStep", b =>
                {
                    b.HasOne("VMTO.Domain.Aggregates.MigrationJob.MigrationJob", null)
                        .WithMany("Steps")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VMTO.Domain.Aggregates.MigrationJob.MigrationJob", b =>
                {
                    b.OwnsOne("VMTO.Domain.ValueObjects.StorageTarget", "StorageTarget", b1 =>
                        {
                            b1.Property<Guid>("MigrationJobId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BucketOrPath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("storage_bucket_or_path");

                            b1.Property<string>("Endpoint")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("storage_endpoint");

                            b1.Property<string>("Region")
                                .HasColumnType("text")
                                .HasColumnName("storage_region");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("storage_type");

                            b1.HasKey("MigrationJobId");

                            b1.ToTable("jobs");

                            b1.WithOwner()
                                .HasForeignKey("MigrationJobId");
                        });

                    b.Navigation("StorageTarget")
                        .IsRequired();
                });

            modelBuilder.Entity("VMTO.Domain.Aggregates.MigrationJob.MigrationJob", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
