name: OSV-Scanner

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  scan-pr:
    name: Scan new vulnerabilities
    if: github.event_name == 'pull_request'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@9a498708959aeaef5ef730655706c5a1df1edbc2 # v2.3.8

  scan-main:
    name: Scan all vulnerabilities
    if: github.event_name == 'push'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@9a498708959aeaef5ef730655706c5a1df1edbc2 # v2.3.8
